### PR TITLE
feat: dashboard trade section and fix trade issues - resolve #52

### LINKED ISSUE #52: dashboard trade

### PR DESCRIPTION
**Pull request by mehranml**

### CODE REVIEW

File: app/dashboard/(components)/Dashboard_Header.tsx [hunk 1]
```diff
@@ -32,32 +32,32 @@ const DashboardHeader = ({ isMobile }: Props) => {
...
+          {/*            formatedString(tab).toLocaleLowerCase() === page*/}
+          {/*              ? "0 0 4px 1px #d9f8ff75"*/}
+          {/*              : "",*/}
+          {/*        }}*/}
+          {/*      >*/}
+          {/*        {tab}*/}
+          {/*      </TabsTrigger>*/}
+          {/*    ))}*/}
+          {/*  </div>*/}
+          {/*</div>*/}
```
Comment (hvmidrezv) [inline app/dashboard/(components)/Dashboard_Header.tsx:60]: remove
